export enum WebSocketKey {
    Unknown = 'Unknown',
    Handshake = 'Handshake',
    ServerStats = 'ServerStats',
    PlexActivity = 'PlexActivity',
    PiHoleActivity = 'PiHoleActivity',
    QBitTorrentStats = 'QBitTorrentStats',
    TautulliStats = 'TautulliStats',
    RadarrActivity = 'RadarrActivity',
    SonarrActivity = 'SonarrActivity',
    LidarrActivity = 'LidarrActivity',
    ReadarrActivity = 'ReadarrActivity',
    DockerAppUpdateProgress = 'DockerAppUpdateProgress',
    UptimeKumaActivity = 'UptimeKumaActivity',
}