// <auto-generated />
using System;
using HomeBoxLanding.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBoxLanding.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230220213444_CreateLinksTable")]
    partial class CreateLinksTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Deploy.Types.DeployRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Links.Types.LinkRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("5d555bdd-d4b3-4b23-be78-e7ecbf25c9c0"),
                            Category = "media",
                            Host = "192.168.1.74",
                            IconUrl = "./assets/plex-logo.png",
                            IsSecure = false,
                            Name = "Plex",
                            Port = 32400,
                            SortOrder = 0,
                            Url = "http://192.168.1.74:32400/"
                        },
                        new
                        {
                            Identifier = new Guid("b3b2e79d-fc39-487e-898f-eee7c04d26d9"),
                            Category = "media",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/overseerr-logo.png",
                            IsSecure = false,
                            Name = "Overseerr",
                            Port = 5055,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:5055/"
                        },
                        new
                        {
                            Identifier = new Guid("aa394ded-2fb1-46f8-a344-da3776500f7f"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/radarr-logo.png",
                            IsSecure = false,
                            Name = "Radarr",
                            Port = 7878,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:7878/"
                        },
                        new
                        {
                            Identifier = new Guid("b96e6d78-13d3-474f-9d3f-367b8a316f45"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/sonarr-logo.png",
                            IsSecure = false,
                            Name = "Sonarr",
                            Port = 8989,
                            SortOrder = 3,
                            Url = "http://192.168.1.25:8989/"
                        },
                        new
                        {
                            Identifier = new Guid("a8867ce6-7e89-4d4f-a37f-17c3866b2be3"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/xteve-logo.png",
                            IsSecure = false,
                            Name = "xTeve",
                            Port = 34400,
                            SortOrder = 4,
                            Url = "http://192.168.1.25:34400/web/"
                        },
                        new
                        {
                            Identifier = new Guid("a75321f8-c057-428f-917f-e933083c86cf"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/mealie-logo.png",
                            IsSecure = false,
                            Name = "Mealie",
                            Port = 9091,
                            SortOrder = 0,
                            Url = "http://192.168.1.161:9091/"
                        },
                        new
                        {
                            Identifier = new Guid("a2b5b22a-972b-4fc0-9057-3426c492e35b"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/planka-logo.png",
                            IsSecure = false,
                            Name = "Planka",
                            Port = 9096,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:9096/"
                        },
                        new
                        {
                            Identifier = new Guid("5926fbfa-b344-4a51-8f62-db40f2cce704"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/trilium-logo.png",
                            IsSecure = false,
                            Name = "Trilium",
                            Port = 9095,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:9095/"
                        },
                        new
                        {
                            Identifier = new Guid("590ffe1a-5dd9-441b-81b7-5abdf4eb18fc"),
                            Category = "productivity",
                            Host = "192.168.1.35",
                            IconUrl = "./assets/octopi-logo.png",
                            IsSecure = false,
                            Name = "OctoPi",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.35/"
                        },
                        new
                        {
                            Identifier = new Guid("b53ba90f-4f9c-49d1-b1b4-f6180f384866"),
                            Category = "productivity",
                            Host = "192.168.1.142",
                            IconUrl = "./assets/mattermost-logo.png",
                            IsSecure = false,
                            Name = "Mattermost",
                            Port = 8065,
                            SortOrder = 4,
                            Url = "http://192.168.1.142:8065/"
                        },
                        new
                        {
                            Identifier = new Guid("a0495abb-58e9-41a4-b8db-23466f8dac95"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/firefly-iii-logo.jpeg",
                            IsSecure = false,
                            Name = "Firefly III",
                            Port = 8282,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8282/"
                        },
                        new
                        {
                            Identifier = new Guid("26dcb458-6b5e-4a5d-98c7-62c2a0e443f3"),
                            Category = "system",
                            Host = "192.168.1.1",
                            IconUrl = "./assets/unifi-logo.png",
                            IsSecure = true,
                            Name = "UniFi Controller",
                            Port = 80,
                            SortOrder = 0,
                            Url = "http://192.168.1.1/"
                        },
                        new
                        {
                            Identifier = new Guid("60585a7e-5c00-4854-ae1e-31ff8e13d75f"),
                            Category = "system",
                            Host = "192.168.1.48",
                            IconUrl = "./assets/synology-logo.png",
                            IsSecure = false,
                            Name = "Synology Dashboard",
                            Port = 5000,
                            SortOrder = 1,
                            Url = "http://192.168.1.48:5000/"
                        },
                        new
                        {
                            Identifier = new Guid("1d6c91f4-c00a-4b3f-ba54-abf54034f8af"),
                            Category = "system",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/prowlarr-logo.png",
                            IsSecure = false,
                            Name = "Prowlarr",
                            Port = 9696,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:9696/"
                        },
                        new
                        {
                            Identifier = new Guid("7f0074b0-f382-4351-a0de-00182c8bccc2"),
                            Category = "system",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/pihole-logo.png",
                            IsSecure = false,
                            Name = "PiHole",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.50/admin/"
                        },
                        new
                        {
                            Identifier = new Guid("b6d36cca-8427-40cd-8c3e-b6934f79253d"),
                            Category = "system",
                            Host = "192.168.1.15",
                            IconUrl = "./assets/proxmox-logo.png",
                            IsSecure = true,
                            Name = "Proxmox",
                            Port = 8006,
                            SortOrder = 4,
                            Url = "https://192.168.1.15:8006/"
                        },
                        new
                        {
                            Identifier = new Guid("f90af342-7d97-4cc5-85ae-2ed55c8423f9"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/influxdb-logo.png",
                            IsSecure = false,
                            Name = "InfluxDB",
                            Port = 8086,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8086/"
                        },
                        new
                        {
                            Identifier = new Guid("b02eee59-5908-4388-a084-81e1c9e8c57d"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/grafana-logo.png",
                            IsSecure = false,
                            Name = "Grafana",
                            Port = 3000,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3000/"
                        },
                        new
                        {
                            Identifier = new Guid("20622552-2f72-4b9b-8f95-7eca979bbe9d"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/tautulli-logo.png",
                            IsSecure = false,
                            Name = "Tautulli",
                            Port = 8181,
                            SortOrder = 7,
                            Url = "http://192.168.1.161:8181/"
                        },
                        new
                        {
                            Identifier = new Guid("ddbd1742-9c1d-4ad0-8299-433cf147f202"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/portainer-logo.png",
                            IsSecure = true,
                            Name = "Portainer",
                            Port = 9443,
                            SortOrder = 0,
                            Url = "https://192.168.1.161:9443/"
                        },
                        new
                        {
                            Identifier = new Guid("2f46896f-445d-41df-9b57-f6ebe5c8dceb"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/flood-logo.png",
                            IsSecure = false,
                            Name = "Flood",
                            Port = 8081,
                            SortOrder = 1,
                            Url = "http://192.168.1.25:8081/"
                        },
                        new
                        {
                            Identifier = new Guid("85b9a3bd-cc19-425f-9d94-db06e1674e87"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/nginx-proxy-manager-logo.png",
                            IsSecure = false,
                            Name = "Nginx Proxy Manager",
                            Port = 81,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:81/"
                        },
                        new
                        {
                            Identifier = new Guid("f0faf07d-5c47-4a3b-b3c0-1e7d982fe444"),
                            Category = "tools",
                            Host = "192.168.1.205",
                            IconUrl = "./assets/homebridge-logo.png",
                            IsSecure = false,
                            Name = "Homebridge",
                            Port = 8581,
                            SortOrder = 3,
                            Url = "http://192.168.1.205:8581/"
                        },
                        new
                        {
                            Identifier = new Guid("24b0fa51-101a-4858-898c-3f4f23844fd6"),
                            Category = "tools",
                            Host = "192.168.1.254",
                            IconUrl = "./assets/home-assistant-logo.png",
                            IsSecure = false,
                            Name = "Home Assistant",
                            Port = 8123,
                            SortOrder = 4,
                            Url = "http://192.168.1.254:8123/"
                        },
                        new
                        {
                            Identifier = new Guid("a037667b-23cb-4bcb-ae4d-c2cd0db99fa3"),
                            Category = "tools",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/phoscon-logo.jpeg",
                            IsSecure = false,
                            Name = "Phoscon",
                            Port = 8080,
                            SortOrder = 5,
                            Url = "http://192.168.1.50:8080/"
                        },
                        new
                        {
                            Identifier = new Guid("24f6048f-3727-4e89-acda-f76355306b42"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/uptime-kuma-logo.png",
                            IsSecure = false,
                            Name = "Uptime Kuma",
                            Port = 3001,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3001/"
                        },
                        new
                        {
                            Identifier = new Guid("70e2f925-3b89-403f-8f8d-cbd50c6ad828"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/tdarr-logo.png",
                            IsSecure = false,
                            Name = "Tdarr",
                            Port = 8265,
                            SortOrder = 7,
                            Url = "http://192.168.1.25:8265/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
