// <auto-generated />
using System;
using HomeBoxLanding.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBoxLanding.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230223160306_CreateBuildsTable")]
    partial class CreateBuildsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Builds.Types.BuildRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Conclusion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Identifier");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Deploys.Types.DeployRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Links.Types.LinkRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("aa9196f0-a0b4-44f4-a42d-dce5e96f82d5"),
                            Category = "media",
                            Host = "192.168.1.74",
                            IconUrl = "./assets/plex-logo.png",
                            IsSecure = false,
                            Name = "Plex",
                            Port = 32400,
                            SortOrder = 0,
                            Url = "http://192.168.1.74:32400/"
                        },
                        new
                        {
                            Identifier = new Guid("f2a0022b-9cca-4477-a681-71df29391d4a"),
                            Category = "media",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/overseerr-logo.png",
                            IsSecure = false,
                            Name = "Overseerr",
                            Port = 5055,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:5055/"
                        },
                        new
                        {
                            Identifier = new Guid("dba56b8f-d320-4a75-be13-58c0cb2f5fd4"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/radarr-logo.png",
                            IsSecure = false,
                            Name = "Radarr",
                            Port = 7878,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:7878/"
                        },
                        new
                        {
                            Identifier = new Guid("75bd3e1b-b0d7-46e6-a124-9e7207efffcc"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/sonarr-logo.png",
                            IsSecure = false,
                            Name = "Sonarr",
                            Port = 8989,
                            SortOrder = 3,
                            Url = "http://192.168.1.25:8989/"
                        },
                        new
                        {
                            Identifier = new Guid("d7f2daa1-5e6f-4578-8428-36a668434d95"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/xteve-logo.png",
                            IsSecure = false,
                            Name = "xTeve",
                            Port = 34400,
                            SortOrder = 4,
                            Url = "http://192.168.1.25:34400/web/"
                        },
                        new
                        {
                            Identifier = new Guid("64064be1-0eef-40ec-9497-8ba56bf38264"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/mealie-logo.png",
                            IsSecure = false,
                            Name = "Mealie",
                            Port = 9091,
                            SortOrder = 0,
                            Url = "http://192.168.1.161:9091/"
                        },
                        new
                        {
                            Identifier = new Guid("27c9ec70-f82d-4883-bcee-c55139979ce9"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/planka-logo.png",
                            IsSecure = false,
                            Name = "Planka",
                            Port = 9096,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:9096/"
                        },
                        new
                        {
                            Identifier = new Guid("fa1bd65e-0868-47b5-9929-8f2876ff2b8f"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/trilium-logo.png",
                            IsSecure = false,
                            Name = "Trilium",
                            Port = 9095,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:9095/"
                        },
                        new
                        {
                            Identifier = new Guid("8cf92cb1-a1e7-4e69-b6e8-6a25c1240eee"),
                            Category = "productivity",
                            Host = "192.168.1.35",
                            IconUrl = "./assets/octopi-logo.png",
                            IsSecure = false,
                            Name = "OctoPi",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.35/"
                        },
                        new
                        {
                            Identifier = new Guid("97dcc1be-3444-4bc1-9e8d-6db637c88dc7"),
                            Category = "productivity",
                            Host = "192.168.1.142",
                            IconUrl = "./assets/mattermost-logo.png",
                            IsSecure = false,
                            Name = "Mattermost",
                            Port = 8065,
                            SortOrder = 4,
                            Url = "http://192.168.1.142:8065/"
                        },
                        new
                        {
                            Identifier = new Guid("4c50f877-d402-4e2f-9d05-4e5689549c53"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/firefly-iii-logo.jpeg",
                            IsSecure = false,
                            Name = "Firefly III",
                            Port = 8282,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8282/"
                        },
                        new
                        {
                            Identifier = new Guid("ab5f271c-9ca8-4fae-bce7-171f46820dad"),
                            Category = "system",
                            Host = "192.168.1.1",
                            IconUrl = "./assets/unifi-logo.png",
                            IsSecure = true,
                            Name = "UniFi Controller",
                            Port = 80,
                            SortOrder = 0,
                            Url = "http://192.168.1.1/"
                        },
                        new
                        {
                            Identifier = new Guid("0008c0fa-edcc-4db0-b6b8-74a8ce4835f5"),
                            Category = "system",
                            Host = "192.168.1.48",
                            IconUrl = "./assets/synology-logo.png",
                            IsSecure = false,
                            Name = "Synology Dashboard",
                            Port = 5000,
                            SortOrder = 1,
                            Url = "http://192.168.1.48:5000/"
                        },
                        new
                        {
                            Identifier = new Guid("8cd5bc38-b560-47e8-97f3-6a4cfb86cf32"),
                            Category = "system",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/prowlarr-logo.png",
                            IsSecure = false,
                            Name = "Prowlarr",
                            Port = 9696,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:9696/"
                        },
                        new
                        {
                            Identifier = new Guid("74c61859-0b88-4557-ba82-0b8f865de4af"),
                            Category = "system",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/pihole-logo.png",
                            IsSecure = false,
                            Name = "PiHole",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.50/admin/"
                        },
                        new
                        {
                            Identifier = new Guid("5a5b4fa9-f89f-4b20-a397-d3d7cb90f8cd"),
                            Category = "system",
                            Host = "192.168.1.15",
                            IconUrl = "./assets/proxmox-logo.png",
                            IsSecure = true,
                            Name = "Proxmox",
                            Port = 8006,
                            SortOrder = 4,
                            Url = "https://192.168.1.15:8006/"
                        },
                        new
                        {
                            Identifier = new Guid("916f1b85-2814-4c4b-88d9-a434b9419941"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/influxdb-logo.png",
                            IsSecure = false,
                            Name = "InfluxDB",
                            Port = 8086,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8086/"
                        },
                        new
                        {
                            Identifier = new Guid("a294ab65-c4b1-4c5d-b1e4-ef3b6d4e39f3"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/grafana-logo.png",
                            IsSecure = false,
                            Name = "Grafana",
                            Port = 3000,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3000/"
                        },
                        new
                        {
                            Identifier = new Guid("7f2864c8-6554-4e5f-94c0-b4f15e874ad0"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/tautulli-logo.png",
                            IsSecure = false,
                            Name = "Tautulli",
                            Port = 8181,
                            SortOrder = 7,
                            Url = "http://192.168.1.161:8181/"
                        },
                        new
                        {
                            Identifier = new Guid("e36b711e-5e00-4dfe-a066-ef835d7890d7"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/portainer-logo.png",
                            IsSecure = true,
                            Name = "Portainer",
                            Port = 9443,
                            SortOrder = 0,
                            Url = "https://192.168.1.161:9443/"
                        },
                        new
                        {
                            Identifier = new Guid("08116dd9-4fd2-4175-a021-ff149823fb4d"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/flood-logo.png",
                            IsSecure = false,
                            Name = "Flood",
                            Port = 8081,
                            SortOrder = 1,
                            Url = "http://192.168.1.25:8081/"
                        },
                        new
                        {
                            Identifier = new Guid("55ec84c8-98cd-4e9d-a5c5-83366a2c1a79"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/nginx-proxy-manager-logo.png",
                            IsSecure = false,
                            Name = "Nginx Proxy Manager",
                            Port = 81,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:81/"
                        },
                        new
                        {
                            Identifier = new Guid("231cd4ff-8f98-4cb3-92ff-d8db8b0f3251"),
                            Category = "tools",
                            Host = "192.168.1.205",
                            IconUrl = "./assets/homebridge-logo.png",
                            IsSecure = false,
                            Name = "Homebridge",
                            Port = 8581,
                            SortOrder = 3,
                            Url = "http://192.168.1.205:8581/"
                        },
                        new
                        {
                            Identifier = new Guid("4be021d3-f975-45ca-9550-a19421ea319e"),
                            Category = "tools",
                            Host = "192.168.1.254",
                            IconUrl = "./assets/home-assistant-logo.png",
                            IsSecure = false,
                            Name = "Home Assistant",
                            Port = 8123,
                            SortOrder = 4,
                            Url = "http://192.168.1.254:8123/"
                        },
                        new
                        {
                            Identifier = new Guid("4c6ffa5d-dab8-4511-8c9b-edb3f1c6ffe7"),
                            Category = "tools",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/phoscon-logo.jpeg",
                            IsSecure = false,
                            Name = "Phoscon",
                            Port = 8080,
                            SortOrder = 5,
                            Url = "http://192.168.1.50:8080/"
                        },
                        new
                        {
                            Identifier = new Guid("2ff48161-923a-471c-b6ea-e2a6a905d7ae"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/uptime-kuma-logo.png",
                            IsSecure = false,
                            Name = "Uptime Kuma",
                            Port = 3001,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3001/"
                        },
                        new
                        {
                            Identifier = new Guid("a493f949-3564-4aa4-88ad-ecd58e7e893b"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/tdarr-logo.png",
                            IsSecure = false,
                            Name = "Tdarr",
                            Port = 8265,
                            SortOrder = 7,
                            Url = "http://192.168.1.25:8265/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
