// <auto-generated />
using System;
using HomeBoxLanding.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBoxLanding.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230427151659_UpdateLinkSortOrderColumnType")]
    partial class UpdateLinkSortOrderColumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Builds.Types.BuildRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Conclusion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GithubBuildReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Identifier");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Deploys.Types.DeployRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Links.Types.LinkRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SortOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("9997a82a-04ed-44d4-83a8-b523f472a950"),
                            Category = "media",
                            Host = "192.168.1.74",
                            IconUrl = "./assets/plex-logo.png",
                            IsSecure = false,
                            Name = "Plex",
                            Port = 32400,
                            SortOrder = "A",
                            Url = "http://192.168.1.74:32400/"
                        },
                        new
                        {
                            Identifier = new Guid("f63af15c-23bf-485f-a5f5-f68f8ac0af5b"),
                            Category = "media",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/overseerr-logo.png",
                            IsSecure = false,
                            Name = "Overseerr",
                            Port = 5055,
                            SortOrder = "B",
                            Url = "http://192.168.1.161:5055/"
                        },
                        new
                        {
                            Identifier = new Guid("87e8fca8-0160-4f2a-87aa-dc3b7f5b632e"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/radarr-logo.png",
                            IsSecure = false,
                            Name = "Radarr",
                            Port = 7878,
                            SortOrder = "C",
                            Url = "http://192.168.1.25:7878/"
                        },
                        new
                        {
                            Identifier = new Guid("e0ca234a-4df0-4f19-8b8b-786499dd9a01"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/sonarr-logo.png",
                            IsSecure = false,
                            Name = "Sonarr",
                            Port = 8989,
                            SortOrder = "D",
                            Url = "http://192.168.1.25:8989/"
                        },
                        new
                        {
                            Identifier = new Guid("c2072fea-73a3-449a-8576-666ac1d72047"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/xteve-logo.png",
                            IsSecure = false,
                            Name = "xTeve",
                            Port = 34400,
                            SortOrder = "E",
                            Url = "http://192.168.1.25:34400/web/"
                        },
                        new
                        {
                            Identifier = new Guid("b71169f0-06eb-4c83-bb46-84ba5e425fe0"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/mealie-logo.png",
                            IsSecure = false,
                            Name = "Mealie",
                            Port = 9091,
                            SortOrder = "F",
                            Url = "http://192.168.1.161:9091/"
                        },
                        new
                        {
                            Identifier = new Guid("77e45f78-d2f3-48f6-8ea6-dcfd9b461acb"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/planka-logo.png",
                            IsSecure = false,
                            Name = "Planka",
                            Port = 9096,
                            SortOrder = "G",
                            Url = "http://192.168.1.161:9096/"
                        },
                        new
                        {
                            Identifier = new Guid("e39520d5-a1c3-4ba0-b292-e8b38682e3bd"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/trilium-logo.png",
                            IsSecure = false,
                            Name = "Trilium",
                            Port = 9095,
                            SortOrder = "H",
                            Url = "http://192.168.1.161:9095/"
                        },
                        new
                        {
                            Identifier = new Guid("f98a4a5b-b45b-4c7e-9339-7ccec4a2ba11"),
                            Category = "productivity",
                            Host = "192.168.1.35",
                            IconUrl = "./assets/octopi-logo.png",
                            IsSecure = false,
                            Name = "OctoPi",
                            Port = 80,
                            SortOrder = "I",
                            Url = "http://192.168.1.35/"
                        },
                        new
                        {
                            Identifier = new Guid("72d955e8-5bbd-4ea4-8cd7-fc8db9ca4add"),
                            Category = "productivity",
                            Host = "192.168.1.142",
                            IconUrl = "./assets/mattermost-logo.png",
                            IsSecure = false,
                            Name = "Mattermost",
                            Port = 8065,
                            SortOrder = "J",
                            Url = "http://192.168.1.142:8065/"
                        },
                        new
                        {
                            Identifier = new Guid("2c1b65ca-e740-4879-917f-50bda0fa6254"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/firefly-iii-logo.jpeg",
                            IsSecure = false,
                            Name = "Firefly III",
                            Port = 8282,
                            SortOrder = "K",
                            Url = "http://192.168.1.161:8282/"
                        },
                        new
                        {
                            Identifier = new Guid("3c9dd86a-08fe-469a-a7c9-29a301dd8bc7"),
                            Category = "system",
                            Host = "192.168.1.1",
                            IconUrl = "./assets/unifi-logo.png",
                            IsSecure = true,
                            Name = "UniFi Controller",
                            Port = 80,
                            SortOrder = "L",
                            Url = "http://192.168.1.1/"
                        },
                        new
                        {
                            Identifier = new Guid("aa78efae-641d-4a8c-a026-46ada84ebff0"),
                            Category = "system",
                            Host = "192.168.1.48",
                            IconUrl = "./assets/synology-logo.png",
                            IsSecure = false,
                            Name = "Synology Dashboard",
                            Port = 5000,
                            SortOrder = "M",
                            Url = "http://192.168.1.48:5000/"
                        },
                        new
                        {
                            Identifier = new Guid("bac0adf8-7b47-4e9e-bd16-694db7e77354"),
                            Category = "system",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/prowlarr-logo.png",
                            IsSecure = false,
                            Name = "Prowlarr",
                            Port = 9696,
                            SortOrder = "N",
                            Url = "http://192.168.1.25:9696/"
                        },
                        new
                        {
                            Identifier = new Guid("ea89d062-2d4c-43a8-8291-a4052411da14"),
                            Category = "system",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/pihole-logo.png",
                            IsSecure = false,
                            Name = "PiHole",
                            Port = 80,
                            SortOrder = "O",
                            Url = "http://192.168.1.50/admin/"
                        },
                        new
                        {
                            Identifier = new Guid("60dd7d27-e471-4748-a4e5-968093be0f46"),
                            Category = "system",
                            Host = "192.168.1.15",
                            IconUrl = "./assets/proxmox-logo.png",
                            IsSecure = true,
                            Name = "Proxmox",
                            Port = 8006,
                            SortOrder = "P",
                            Url = "https://192.168.1.15:8006/"
                        },
                        new
                        {
                            Identifier = new Guid("f43dcb52-8e93-494c-8823-1f8e8c38f991"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/influxdb-logo.png",
                            IsSecure = false,
                            Name = "InfluxDB",
                            Port = 8086,
                            SortOrder = "Q",
                            Url = "http://192.168.1.161:8086/"
                        },
                        new
                        {
                            Identifier = new Guid("b9b1b3de-ecf0-47f9-8ea4-71ed409d8bd2"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/grafana-logo.png",
                            IsSecure = false,
                            Name = "Grafana",
                            Port = 3000,
                            SortOrder = "R",
                            Url = "http://192.168.1.161:3000/"
                        },
                        new
                        {
                            Identifier = new Guid("0bcca72c-cc40-4804-92a0-924e716755aa"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/tautulli-logo.png",
                            IsSecure = false,
                            Name = "Tautulli",
                            Port = 8181,
                            SortOrder = "S",
                            Url = "http://192.168.1.161:8181/"
                        },
                        new
                        {
                            Identifier = new Guid("6f58e028-c5f0-4e62-b8a4-d966444820e5"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/portainer-logo.png",
                            IsSecure = true,
                            Name = "Portainer",
                            Port = 9443,
                            SortOrder = "T",
                            Url = "https://192.168.1.161:9443/"
                        },
                        new
                        {
                            Identifier = new Guid("5dad71a9-a5c8-4bd7-a643-c4d42554013a"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/flood-logo.png",
                            IsSecure = false,
                            Name = "Flood",
                            Port = 8081,
                            SortOrder = "U",
                            Url = "http://192.168.1.25:8081/"
                        },
                        new
                        {
                            Identifier = new Guid("6da3a0b8-ca77-44dd-bfb9-66556f9dc875"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/nginx-proxy-manager-logo.png",
                            IsSecure = false,
                            Name = "Nginx Proxy Manager",
                            Port = 81,
                            SortOrder = "V",
                            Url = "http://192.168.1.161:81/"
                        },
                        new
                        {
                            Identifier = new Guid("6a9eaa9b-027e-4417-8ec5-73235571a57e"),
                            Category = "tools",
                            Host = "192.168.1.205",
                            IconUrl = "./assets/homebridge-logo.png",
                            IsSecure = false,
                            Name = "Homebridge",
                            Port = 8581,
                            SortOrder = "X",
                            Url = "http://192.168.1.205:8581/"
                        },
                        new
                        {
                            Identifier = new Guid("0c997358-2c7e-49b2-9746-24001d03a349"),
                            Category = "tools",
                            Host = "192.168.1.254",
                            IconUrl = "./assets/home-assistant-logo.png",
                            IsSecure = false,
                            Name = "Home Assistant",
                            Port = 8123,
                            SortOrder = "Y",
                            Url = "http://192.168.1.254:8123/"
                        },
                        new
                        {
                            Identifier = new Guid("9abce3d0-836b-4dfb-b92c-9f2251f33abc"),
                            Category = "tools",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/phoscon-logo.jpeg",
                            IsSecure = false,
                            Name = "Phoscon",
                            Port = 8080,
                            SortOrder = "Z",
                            Url = "http://192.168.1.50:8080/"
                        },
                        new
                        {
                            Identifier = new Guid("ddb9464e-5c2a-43b5-b0ef-edf15b03c00d"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/uptime-kuma-logo.png",
                            IsSecure = false,
                            Name = "Uptime Kuma",
                            Port = 3001,
                            SortOrder = "ZA",
                            Url = "http://192.168.1.161:3001/"
                        },
                        new
                        {
                            Identifier = new Guid("a4941178-0918-435a-8b05-994cd610a64f"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/tdarr-logo.png",
                            IsSecure = false,
                            Name = "Tdarr",
                            Port = 8265,
                            SortOrder = "ZB",
                            Url = "http://192.168.1.25:8265/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
