// <auto-generated />
using System;
using HomeBoxLanding.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBoxLanding.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230223205838_AddGithubBuildReferenceToBuildsTable")]
    partial class AddGithubBuildReferenceToBuildsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Builds.Types.BuildRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Conclusion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GithubBuildReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Identifier");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Deploys.Types.DeployRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("HomeBoxLanding.Api.Features.Links.Types.LinkRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identifier");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("e559abdc-c8b9-460f-be48-87f8e77c24dd"),
                            Category = "media",
                            Host = "192.168.1.74",
                            IconUrl = "./assets/plex-logo.png",
                            IsSecure = false,
                            Name = "Plex",
                            Port = 32400,
                            SortOrder = 0,
                            Url = "http://192.168.1.74:32400/"
                        },
                        new
                        {
                            Identifier = new Guid("6930ae90-d6f8-40b9-86a0-740e305ff411"),
                            Category = "media",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/overseerr-logo.png",
                            IsSecure = false,
                            Name = "Overseerr",
                            Port = 5055,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:5055/"
                        },
                        new
                        {
                            Identifier = new Guid("99b05a22-777c-43f2-b8fd-f96f3baa9c69"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/radarr-logo.png",
                            IsSecure = false,
                            Name = "Radarr",
                            Port = 7878,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:7878/"
                        },
                        new
                        {
                            Identifier = new Guid("f91ff8be-d354-469f-a6a5-fccfaa640cb3"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/sonarr-logo.png",
                            IsSecure = false,
                            Name = "Sonarr",
                            Port = 8989,
                            SortOrder = 3,
                            Url = "http://192.168.1.25:8989/"
                        },
                        new
                        {
                            Identifier = new Guid("e96026d8-e698-4a07-8a38-9ba98ae73403"),
                            Category = "media",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/xteve-logo.png",
                            IsSecure = false,
                            Name = "xTeve",
                            Port = 34400,
                            SortOrder = 4,
                            Url = "http://192.168.1.25:34400/web/"
                        },
                        new
                        {
                            Identifier = new Guid("4c4243e7-e116-4d0d-a8fb-26249576ea57"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/mealie-logo.png",
                            IsSecure = false,
                            Name = "Mealie",
                            Port = 9091,
                            SortOrder = 0,
                            Url = "http://192.168.1.161:9091/"
                        },
                        new
                        {
                            Identifier = new Guid("5f9a9237-5d65-4daf-81ed-9b4ebd50c73c"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/planka-logo.png",
                            IsSecure = false,
                            Name = "Planka",
                            Port = 9096,
                            SortOrder = 1,
                            Url = "http://192.168.1.161:9096/"
                        },
                        new
                        {
                            Identifier = new Guid("dd8d6898-42e8-499a-8c9f-33e15ef01ca0"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/trilium-logo.png",
                            IsSecure = false,
                            Name = "Trilium",
                            Port = 9095,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:9095/"
                        },
                        new
                        {
                            Identifier = new Guid("9ad28ba4-a3ae-4d61-a4d4-cd4316e1813b"),
                            Category = "productivity",
                            Host = "192.168.1.35",
                            IconUrl = "./assets/octopi-logo.png",
                            IsSecure = false,
                            Name = "OctoPi",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.35/"
                        },
                        new
                        {
                            Identifier = new Guid("4e234356-b63d-4fa1-a4d9-3324ab9d027c"),
                            Category = "productivity",
                            Host = "192.168.1.142",
                            IconUrl = "./assets/mattermost-logo.png",
                            IsSecure = false,
                            Name = "Mattermost",
                            Port = 8065,
                            SortOrder = 4,
                            Url = "http://192.168.1.142:8065/"
                        },
                        new
                        {
                            Identifier = new Guid("d53f711d-a744-4b58-8c91-9eecddab190a"),
                            Category = "productivity",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/firefly-iii-logo.jpeg",
                            IsSecure = false,
                            Name = "Firefly III",
                            Port = 8282,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8282/"
                        },
                        new
                        {
                            Identifier = new Guid("b3d8bf34-a31d-403b-a16d-05b8d5bf4532"),
                            Category = "system",
                            Host = "192.168.1.1",
                            IconUrl = "./assets/unifi-logo.png",
                            IsSecure = true,
                            Name = "UniFi Controller",
                            Port = 80,
                            SortOrder = 0,
                            Url = "http://192.168.1.1/"
                        },
                        new
                        {
                            Identifier = new Guid("d31d5666-1ff8-415e-a613-51f71ed67512"),
                            Category = "system",
                            Host = "192.168.1.48",
                            IconUrl = "./assets/synology-logo.png",
                            IsSecure = false,
                            Name = "Synology Dashboard",
                            Port = 5000,
                            SortOrder = 1,
                            Url = "http://192.168.1.48:5000/"
                        },
                        new
                        {
                            Identifier = new Guid("080aa5c4-b63c-4f3c-8767-72e4775a7034"),
                            Category = "system",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/prowlarr-logo.png",
                            IsSecure = false,
                            Name = "Prowlarr",
                            Port = 9696,
                            SortOrder = 2,
                            Url = "http://192.168.1.25:9696/"
                        },
                        new
                        {
                            Identifier = new Guid("12e5579b-9f42-45a6-88d1-0e2c82c935c2"),
                            Category = "system",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/pihole-logo.png",
                            IsSecure = false,
                            Name = "PiHole",
                            Port = 80,
                            SortOrder = 3,
                            Url = "http://192.168.1.50/admin/"
                        },
                        new
                        {
                            Identifier = new Guid("70607e71-c3f4-4356-b90d-2a71c0e0f0fb"),
                            Category = "system",
                            Host = "192.168.1.15",
                            IconUrl = "./assets/proxmox-logo.png",
                            IsSecure = true,
                            Name = "Proxmox",
                            Port = 8006,
                            SortOrder = 4,
                            Url = "https://192.168.1.15:8006/"
                        },
                        new
                        {
                            Identifier = new Guid("ed29ec31-4e0b-4ce2-9dcb-8b5e440b360d"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/influxdb-logo.png",
                            IsSecure = false,
                            Name = "InfluxDB",
                            Port = 8086,
                            SortOrder = 5,
                            Url = "http://192.168.1.161:8086/"
                        },
                        new
                        {
                            Identifier = new Guid("d6d21105-2e34-448a-b925-ffb954aabe91"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/grafana-logo.png",
                            IsSecure = false,
                            Name = "Grafana",
                            Port = 3000,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3000/"
                        },
                        new
                        {
                            Identifier = new Guid("413560d9-c7f7-4851-9957-433e6470b963"),
                            Category = "system",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/tautulli-logo.png",
                            IsSecure = false,
                            Name = "Tautulli",
                            Port = 8181,
                            SortOrder = 7,
                            Url = "http://192.168.1.161:8181/"
                        },
                        new
                        {
                            Identifier = new Guid("939a9a50-b89f-4d39-bea2-a8bc8655466d"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/portainer-logo.png",
                            IsSecure = true,
                            Name = "Portainer",
                            Port = 9443,
                            SortOrder = 0,
                            Url = "https://192.168.1.161:9443/"
                        },
                        new
                        {
                            Identifier = new Guid("bfc616da-0a40-4843-a984-c9f28e8dc32c"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/flood-logo.png",
                            IsSecure = false,
                            Name = "Flood",
                            Port = 8081,
                            SortOrder = 1,
                            Url = "http://192.168.1.25:8081/"
                        },
                        new
                        {
                            Identifier = new Guid("81628985-ffc6-4742-b2af-9f83c86ce490"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/nginx-proxy-manager-logo.png",
                            IsSecure = false,
                            Name = "Nginx Proxy Manager",
                            Port = 81,
                            SortOrder = 2,
                            Url = "http://192.168.1.161:81/"
                        },
                        new
                        {
                            Identifier = new Guid("39cad5ec-eea5-4114-b67c-e5cfbd7037be"),
                            Category = "tools",
                            Host = "192.168.1.205",
                            IconUrl = "./assets/homebridge-logo.png",
                            IsSecure = false,
                            Name = "Homebridge",
                            Port = 8581,
                            SortOrder = 3,
                            Url = "http://192.168.1.205:8581/"
                        },
                        new
                        {
                            Identifier = new Guid("5015a5c8-3c68-4c67-bf8e-a2caa89da4f0"),
                            Category = "tools",
                            Host = "192.168.1.254",
                            IconUrl = "./assets/home-assistant-logo.png",
                            IsSecure = false,
                            Name = "Home Assistant",
                            Port = 8123,
                            SortOrder = 4,
                            Url = "http://192.168.1.254:8123/"
                        },
                        new
                        {
                            Identifier = new Guid("81fd41dd-f3d1-4079-aff8-fa855effd88f"),
                            Category = "tools",
                            Host = "192.168.1.50",
                            IconUrl = "./assets/phoscon-logo.jpeg",
                            IsSecure = false,
                            Name = "Phoscon",
                            Port = 8080,
                            SortOrder = 5,
                            Url = "http://192.168.1.50:8080/"
                        },
                        new
                        {
                            Identifier = new Guid("a75ee54b-81d2-4878-9e8e-1c5cdacca44b"),
                            Category = "tools",
                            Host = "192.168.1.161",
                            IconUrl = "./assets/uptime-kuma-logo.png",
                            IsSecure = false,
                            Name = "Uptime Kuma",
                            Port = 3001,
                            SortOrder = 6,
                            Url = "http://192.168.1.161:3001/"
                        },
                        new
                        {
                            Identifier = new Guid("ce1924d0-b558-4766-a0d0-6fa4eca5e383"),
                            Category = "tools",
                            Host = "192.168.1.25",
                            IconUrl = "./assets/tdarr-logo.png",
                            IsSecure = false,
                            Name = "Tdarr",
                            Port = 8265,
                            SortOrder = 7,
                            Url = "http://192.168.1.25:8265/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
